version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '696896681' &&
    assertion.ref == 'refs/heads/main'

scope:
  create-tag:
    rule:
      if: |-
        assertion.job_workflow_ref == "abcxyz/pkg/.github/workflows/create-tag.yml@refs/heads/main" &&
        assertion.workflow_ref.startsWith("abcxyz/jvs-plugin-github/.github/workflows/create-tag.yml") &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'jvs-plugin-github'
    permissions:
      contents: 'write'

