name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:


concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-test-unit'
  cancel-in-progress: true

jobs:
  # Linting jobs - terraform, go, java
  yaml_lint:
    uses: 'abcxyz/pkg/.github/workflows/yaml-lint.yml@main' # ratchet:exclude

  go_lint:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main' # ratchet:exclude
    with:
      go_version: '1.21'

  # Unit tests - go, java
  go_test:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@main' # ratchet:exclude
    with:
      go_version: '1.21'

  lint_and_unit:
    runs-on: 'ubuntu-latest'
    needs:
      - 'go_lint'
      - 'go_test'
      - 'yaml_lint'
    steps:
      - run: 'echo prechecks complete'
